### PR TITLE
dotfiles: install neovim and coc.vim

### PR DESCRIPTION
**Pull request by croaky**
Attempt to improve autocompletion.

### CODE REVIEW

**Comment by geoffharcourt** [comment]
Do it!

**Comment by croaky** [comment]
Installed coc.vim today, played around it with it in Ruby, TypeScript, and Go. Overall better LSP experience. Planning to bring back ALE for linting drawer and auto-formatting

https://github.com/croaky/laptop/commit/d1477b29f4897445e33d12bb2356dd5f45c06161
https://github.com/croaky/laptop/commit/101b3c801a040ac2156ced55e4bf12b4bb0a7998

**Comment by geoffharcourt** [comment]
@croaky I've found that for some reason (and this has been felt by members of our team with different vim setups) that coc seems to have much faster TS feedback on diagnostics. At this point I'm using ALE for all diagnostics and linting except TS.

**Comment by croaky** [comment]
@geoffharcourt That's interesting. I've also noticed slowness in TS for coc.vim. `"tsserver.npm": "/Users/croaky/.asdf/shims/npm"`, maybe `typingsCacheLocation` or something could help.

I don't really understand why there are so many linter settings in https://github.com/neoclide/coc-tsserver#configuration-options. I would think it would totally delegate to `tslint` or `tsconfig` files.

**Comment by geoffharcourt** [comment]
Ah @croaky we're not using TSLint, we're using eslint-typescript, which might explain some of this. Our impression is that TSLint has been deprecated (though it still works) and won't be the standard tool for long.

**Comment by croaky** [comment]
Aha, I see! Thank you, both comments are helpful

**Pull request closed without merging**
